export const NS = {
  page: {
    title: "بەخشین",
    subtitle:
      "ڕێکخستنی پەڕەی بەخشین، ژمارەکانی بانک، و بەڕێوەبردنی داواکارییەکان.",
  },
  tab: {
    settings: "ڕێکخستنەکان",
    archive: "ئەرشیف",
    financial: "دارایی",
  },
  breadcrumb: {
    dashboard: "داشبۆرد",
    donations: "بەخشین",
  },
  settings: {
    title: "ڕێکخستنەکانی پەڕە",
    subtitle: "وێنەی سەرپەڕە، ژمارەکانی بانک، و چالاککردنی فۆرمەکان.",
    heroImage: "وێنەی سەرپەڕە",
    heroImageHelper: "وێنەی پاشبنەمای بەشی Hero لە ماڵپەڕدا.",
    titles: "ناونیشانەکان (ئارەزوومەندانە)",
    titleCkb: "ناونیشان (سورانی)",
    titleKmr: "ناونیشان (کرمانجی)",
    descriptions: "پێناسەکان (ئارەزوومەندانە)",
    descriptionCkb: "پێناسە (سورانی)",
    descriptionKmr: "پێناسە (کرمانجی)",
    bank: "زانیاری بانک",
    bankName: "ناوی بانک",
    accountName: "ناوی هەژمار",
    accountNumber: "ژمارەی هەژماری FIB",
    accountNumberHelper: "لە بەشی کۆتایی پەڕەدا پیشان دەدرێت.",
    iban: "ژمارەی FastPay",
    ibanHelper: "لە APIدا وەک iban هەڵدەگیرێت؛ لە ماڵپەڕدا FastPay پیشان دەدرێت.",
    swiftCode: "SWIFT",
    paymentInstructionsCkb: "ڕێنمایی پارەدان (سورانی)",
    paymentInstructionsKmr: "ڕێنمایی پارەدان (کرمانجی)",
    toggles: "چالاککردنی فۆرمەکان",
    financialEnabled: "بەخشینی دارایی (FINANCIAL)",
    financialEnabledHelper:
      "فۆرم و کارتی دارایی لە ماڵپەڕدا پیشان بدە. کاتێک ناچالاک بێت، ناردنی مەبەست (POST /financial) ڕەتدەکرێتەوە.",
    archiveEnabled: "بەخشینی ئەرشیف (ARCHIVE)",
    archiveEnabledHelper:
      "فۆرم و کارتەکانی ئەرشیف لە ماڵپەڕدا پیشان بدە. کاتێک ناچالاک بێت، ناردنی پێشکەش (POST /archive) ڕەتدەکرێتەوە.",
    typesTitle: "جۆرەکانی بەخشین (لە API)",
    typesSubtitle:
      "GET /types لە ئاڵاگۆڕەکانی ڕێکخستنەوە دروست دەبێت — خشتەی جیاگانە نییە.",
    typeEnabled: "چالاک",
    typeDisabled: "ناچالاک",
    save: "پاشەکەوتکردن",
    saved: "ڕێکخستنەکان پاشەکەوت کران.",
  },
  archive: {
    title: "داواکارییەکانی ئەرشیف",
    subtitle: "پێشکەشکردنی ماددەی ئەرشیفی لە ماڵپەڕەوە.",
    search: "گەڕان بە ناو، تەلەفۆن، یان ناونیشان…",
    empty: "هیچ داواکارییەک نییە.",
    sheetTitle: (id: string) => `داواکاری #${id}`,
    donorName: "ناوی بەخشەر",
    phone: "ژمارەی پەیوەندی",
    email: "ئیمەیڵ",
    materialType: "جۆری ماددە",
    registerName: "ناوی تۆمار",
    description: "تێبینی",
    attachment: "هاوپێچ",
    estimatedDate: "بەرواری مەزەندە",
    status: "دۆخ",
    createdAt: "بەرواری ناردن",
    changeStatus: "گۆڕینی دۆخ",
  },
  financial: {
    title: "مەبەستی بەخشینی دارایی",
    subtitle: "تۆمارکردنی مەبەستی گواستنەوەی دەستی لە ماڵپەڕەوە.",
    search: "گەڕان بە ناو، بڕ، یان دراو…",
    empty: "هیچ مەبەستێک نییە.",
    sheetTitle: (id: string) => `مەبەست #${id}`,
    donorName: "ناوی بەخشەر",
    email: "ئیمەیڵ",
    phone: "تەلەفۆن",
    amount: "بڕ",
    currency: "دراو",
    paymentMethod: "ڕێگای پارەدان",
    transactionReference: "ژمارەی مامەڵە",
    message: "پەیام",
    status: "دۆخ",
    createdAt: "بەرواری ناردن",
    changeStatus: "گۆڕینی دۆخ",
  },
  status: {
    all: "هەموو",
    NEW: "نوێ",
    PENDING: "چاوەڕوان",
    IN_REVIEW: "لە پێداچوونەوەدا",
    APPROVED: "پەسەندکراو",
    COMPLETED: "تەواو",
    REJECTED: "ڕەتکراو",
    CLOSED: "داخراو",
  },
  paymentMethod: {
    BANK_TRANSFER: "گواستنەوەی بانکی",
  },
  table: {
    id: "#",
    donor: "بەخشەر",
    contact: "پەیوەندی",
    type: "جۆر",
    amount: "بڕ",
    status: "دۆخ",
    date: "بەروار",
    actions: "کردارەکان",
    view: "بینین",
    page: (from: string, to: string, total: string) =>
      `${from}–${to} لە ${total}`,
  },
  filter: {
    status: "دۆخ",
    clear: "پاککردنەوە",
  },
  error: {
    generic: "هەڵەیەک ڕوویدا. دووبارە هەوڵ بدەرەوە.",
    retry: "دووبارە هەوڵبدەرەوە",
  },
  toast: {
    statusUpdated: "دۆخ نوێکرایەوە.",
    copied: "لە کلیپبۆرددا کۆپی کرا.",
  },
  action: {
    view: "بینین",
    openAttachment: "کردنەوەی هاوپێچ",
  },
} as const
