export const NS = {
  title: "پەیوەندی",
  subtitle: "بینین، گەڕان و بەڕێوەبردنی نووسینگەکانی پەیوەندی",
  count: (n: string) => `کۆی ${n} نووسینگە`,
  new: "نووسینگەی نوێ",
  page: {
    title: "پەڕەی پەیوەندی",
    previewHint: "ئەمە وەک پەڕەی /contact لە سایت دەردەکەوێت.",
    subtitleSimple:
      "هەر بەشێک = یەک نووسینگە لە پەڕەی پەیوەندیدا. زیاد بکە، دواتر زانیارییەکەی پڕ بکەرەوە.",
    sectionsTitle: "نووسینگەکان",
    sectionLabel: (n: string) => `بەش ${n}`,
    previewHeroEmpty: "هێشتا نووسینگەیەک زیاد نەکراوە.",
    previewEmpty: "هیچ نووسینگەیەک نییە",
    previewEmptyHint: "یەکەم نووسینگە زیاد بکە، دواتر ناوەڕۆکی پڕ بکەرەوە.",
  },
  section: {
    unnamed: "نووسینگەی بێ ناونیشان",
  },
  search_placeholder: "گەڕان لە ناونیشان، ناونیشان، تەلەفۆن، یان ئیمەیڵ…",
  filter: {
    status_all: "هەموو دۆخەکان",
    active: "چالاک",
    inactive: "ناچالاک",
    lang_all: "هەموو زمانەکان",
    reset: "پاککردنەوە",
  },
  status: {
    active: "چالاک",
    inactive: "ناچالاک",
    active_helper: "نووسینگەکە لەسەر ماڵپەڕ بەردەستە.",
    inactive_helper: "نووسینگەکە لەسەر ماڵپەڕ دەردەکەوێت تەنها کاتێک چالاک بێت.",
  },
  lang: {
    ckb: "سۆرانی",
    kmr: "کورمانجی",
  },
  table: {
    id: "#",
    slugs: "سلەگەکان",
    title: "ناونیشان",
    contact: "پەیوەندی",
    language: "زمان",
    status: "دۆخ",
    date: "بەروار",
    actions: "",
  },
  action: {
    view: "بینین",
    edit: "دەستکاری",
    delete: "سڕینەوە",
    back: "گەڕانەوە",
    save: "پاشەکەوتکردن",
    saving: "پاشەکەوتکردن…",
    cancel: "هەڵوەشاندنەوە",
    editPage: "دەستکاری پەڕە",
    backToPreview: "گەڕانەوە بۆ پیشاندان",
    addOffice: "زیادکردنی نووسینگە",
  },
  empty: {
    list: "هیچ نووسینگەیەک نەدۆزرایەوە",
    no_body: "وەسف بۆ ئەم زمانە بەردەست نییە.",
  },
  breadcrumb: {
    dashboard: "داشبۆرد",
    contact: "پەیوەندی",
    new: "نووسینگەی نوێ",
    edit: "دەستکاری",
  },
  detail: {
    phone: "تەلەفۆن",
    secondary_phone: "تەلەفۆنی دووەم",
    email: "ئیمەیڵ",
    address: "ناونیشان",
    working_hours: "کاتەکانی کار",
    map: "نەخشە",
    description: "وەسف",
  },
  sidebar: {
    visibility: "دەرکەوتن",
    contact_info: "زانیاری پەیوەندی",
    completion: "تەواوبوون",
    completion_hint: "تەواو: ناونیشان، ناونیشان، کاتەکانی کار، وەسف",
    languages: "زمانەکان",
    system: "زانیاری سیستەم",
    id: "ناسنامە",
    created: "دروستکراوە",
    updated: "نوێکراوەتەوە",
  },
  form: {
    slugs: "سلەگەکان",
    slug_ckb: "سلەگی سۆرانی",
    slug_kmr: "سلەگی کورمانجی",
    slug_ckb_hint: "ناسەری URL — کاراکتەری ASCII یان کوردی",
    slug_kmr_hint: "ئەگەر بۆشێت، سلەگی سۆرانی بەکاردێت",
    slug_required: "پێویستە",
    slug_optional: "ئیختیاری",
    title: "ناونیشان",
    subtitle: "ژێرناونیشان",
    address: "ناونیشان",
    working_hours: "کاتەکانی کار",
    description: "وەسف",
    phone: "تەلەفۆن",
    secondary_phone: "تەلەفۆنی دووەم",
    email: "ئیمەیڵ",
    map_embed_url: "لینکی نەخشە (embed)",
    latitude: "پانی",
    longitude: "درێژی",
    dirty: "گۆڕانکارییە پاشەکەوتنەکراوەکان",
    clean: "هیچ گۆڕانکارییەک نییە",
  },
  validation: {
    languageRequired: "لانیکەم یەک زمان هەڵبژێرە",
  },
  toast: {
    saved: "پاشەکەوت کرا",
    deleted: "سڕایەوە",
  },
  error: {
    validation: "تکایە هەڵەکان چاک بکە",
    load: "بارکردن سەرکەوتوو نەبوو",
    retry: "دووبارە هەوڵبدەرەوە",
  },
  not_found: {
    title: "نووسینگەکە نەدۆزرایەوە",
    cta: "گەڕانەوە بۆ لیست",
  },
  delete: {
    title: "سڕینەوەی نووسینگە",
    description: (name: string) =>
      `دڵنیایت لە سڕینەوەی «${name}»؟ ئەم کردارە ناگەڕێتەوە.`,
    confirm: "دڵنیام",
    cancel: "هەڵوەشاندنەوە",
  },
} as const

export function truncateTitle(s: string, max = 48) {
  const t = s.trim()
  if (t.length <= max) return t
  return `${t.slice(0, max)}…`
}
