/** Central CKB copy for the services module (verbatim from spec §11). */

export const NS = {
  dash: "—",
  error: {
    generic: "هەڵەیەک ڕوویدا. دووبارە هەوڵبدەرەوە.",
    retry: "دووبارە هەوڵبدەرەوە",
  },
  page: {
    title: "خزمەتگوزارییەکان",
    subtitle: "بەڕێوەبردنی هەموو خزمەتگوزاری و چالاکییەکانی دەزگا",
  },
  breadcrumb: {
    dashboard: "داشبۆرد",
    services: "خزمەتگوزارییەکان",
    new: "خزمەتگوزاری نوێ",
    edit: "دەستکاری خزمەتگوزاری",
  },
  action: {
    new: "خزمەتگوزاری نوێ",
    view: "بینین",
    edit: "دەستکاری",
    delete: "سڕینەوە",
    back: "گەڕانەوە",
    save: "پاشەکەوتکردن",
    saving: "پاشەکەوتکردن…",
    cancel: "هەڵوەشاندنەوە",
    change: "گۆڕین",
    reset_filters: "پاککردنەوەی فلتەرەکان",
    add_collection: "کۆکراوەی نوێ",
    add_first_collection: "یەکەم کۆکراوە",
    add_file: "زیادکردنی فایل",
    copy_url: "لەبەرگرتنەوەی ناونیشانی URL",
    share: "هاوبەشکردن",
    view_on_site: "بینین لە سایت",
    publish_now: "ئێستا بڵاوبکەوە",
    clear_publish: "پاککردنەوە",
    bulk_delete: "سڕینەوەی هەڵبژێردراوەکان",
    bulk_cancel: "هەڵوەشاندنەوەی هەڵبژاردن",
    remove_cover: "سڕینەوە",
    use_url_instead: "یان لینکی URL بەکاربهێنە",
    upload: "بارکردن",
    upload_files: "بارکردنی فایلەکان",
    add_file_by_url: "زیادکردنی فایل بە URL",
    create: "دروستکردن",
  },
  filter: {
    search_placeholder: "گەڕان لە ناونیشان، شوێن، یان جۆر",
    all_statuses: "هەموو دۆخەکان",
    published: "بڵاوکراوە",
    draft: "ڕەشنووس",
    all_types: "هەموو جۆرەکان",
    all_active: "هەردووکیان",
    only_active: "تەنیا چالاک",
    only_inactive: "تەنیا ناچالاک",
    lang_ckb_only: "تەنیا سۆرانی",
    lang_kmr_only: "تەنیا کورمانجی",
    lang_both: "هەردووکیان",
  },
  status: {
    published: "بڵاوکراوە",
    scheduled: "کاتبۆداندراو",
    draft: "ڕەشنووس",
    inactive: "ناچالاک",
    contextPublished: (date: string) => `بڵاوکراوەتەوە لە ${date}`,
    contextScheduled: (date: string) => `کاتبۆداندراوە بۆ ${date}`,
    contextDraft: "ڕەشنووس — لە چاوەڕێی بڵاوکردنەوەدا",
    contextInactive: "ناچالاککراوە",
  },
  active: {
    label: "چالاک",
    on: "چالاکە",
    off: "ناچالاکە",
    helper: "ناچالاککردن خزمەتگوزارییەکە لە سایتدا نادیار دەکات بەبێ ئەوەی بسڕدرێتەوە.",
    formHelper: "خزمەتگوزاری ناچالاک لە سایتدا دەرناکەوێت",
    toggleOn: "چالاک کرا",
    toggleOff: "ناچالاک کرا",
  },
  col: {
    cover: "ڕووکار",
    title: "ناونیشان",
    type: "جۆر",
    status: "دۆخ",
    location: "شوێن",
    published: "بەرواری بڵاوکردنەوە",
    media: "میدیا",
    actions: "کردارەکان",
  },
  section: {
    visibility: "چالاکی",
    publish: "بەرواری بڵاوکردنەوە",
    type: "جۆری خزمەتگوزاری",
    location: "شوێن",
    languages: "زمانەکان",
    dates: "بەروارەکان",
    system: "زانیاری سیستەم",
    actions: "کردارەکان",
    collections: "کۆکراوەکانی میدیا",
    collectionsDetail: "کۆکراوەکان",
    general: "زانیاری گشتی",
    languageContent: "ناوەڕۆکی زمانەکان",
    coverHero: "کافەر / هێرۆ",
    mediaCollections: "کۆمەڵە میدیاکان",
    publishing: "بڵاوکردنەوە",
  },
  field: {
    titleCkb: "ناونیشانی خزمەتگوزاری بە سۆرانی…",
    titleKmr: "Sernavê xizmetê bi Kurmancî…",
    bodyCkb: "وەسفی خزمەتگوزارییەکەت لێرە بنووسە…",
    bodyKmr: "Vekolîna xizmeta xwe li vir binivîse…",
    location: "شوێن یان ئامادەبوون لە ئەنڵاین…",
    locationHelper: "(تەنیا یەک شوێن بۆ هەردوو زمان)",
    typeHelper: "بۆ نموونە: ڕاهێنان، چالاکی، وۆرکشۆپ، کۆنفرانس…",
    typeRequired: "جۆری خزمەتگوزاری پێویستە",
    publishHelper:
      "بەرواری داهاتوو واتە کاتبۆداندراو، بەرواری ڕابردوو واتە بڵاوکراوە.",
    coverDrop: "وێنە و فایلەکانت دابنێ یان کلیک بکە بۆ هەڵبژاردن",
    coverHelper: "PNG، JPEG، WEBP یان MP4 · زۆرترین قەبارە ٢٠ MB",
    coverNotSelected: "کافەر هەڵنەبژێردراوە",
    coverMediaUrl: "coverMediaUrl",
    sortOrder: "sortOrder",
    thumbnailUrl: "thumbnailUrl",
    fileUrl: "fileUrl",
  },
  collection: {
    namePlaceholder: "ناوی کۆکراوە…",
    mediaTypeImage: "وێنە",
    mediaTypeVideo: "ڤیدیۆ",
    mediaTypeAudio: "دەنگ",
    mediaTypeLabel: "جۆری میدیا",
    addButton: "زیادکردن",
    fileCount: (count: string) => `${count} فایل`,
    emptyFiles: "هیچ فایلێک لەم کۆکراوەیەدا نییە",
    deleteTitle: "سڕینەوەی ئەم کۆکراوەیە؟",
    deleteBody: (count: string) => `${count} فایلیش لەگەڵیدا دەسڕێتەوە.`,
    newSection: "کۆکراوەکانی میدیا",
    sortOrderLabel: "ڕیزکردن",
  },
  file: {
    sheetTitle: "دەستکاری فایل",
    caption: "نووسە",
    title: "ناونیشان",
    description: "وەسف",
    captionPlaceholder: "نووسەی کورت لەژێر وێنەدا…",
    titlePlaceholder: "ناونیشانی فۆڕماڵ…",
    metadataTitle: "زانیاری تەکنیکی",
    metadataFormat: "فۆڕمات",
    metadataResolution: "پاژەکی",
    metadataDuration: "ماوە",
    metadataCodec: "کۆدیک",
    metadataBitrate: "بایترەیت",
    metadataSize: "قەبارە",
    metadataAutoTooltip: "زانیاری بە شێوەی خۆکار دۆزراوەتەوە",
    delete: "سڕینەوەی فایل",
    captionCkb: "نووسە CKB",
    titleCkb: "ناونیشان CKB",
    descriptionCkb: "وەسف CKB",
    editInline: "دەستکاری لە فۆڕم",
    openSheet: "کردنەوەی پانێڵی تەواو",
  },
  list: {
    totalCount: (count: string) => `کۆی ${count} خزمەتگوزاری`,
    selectedCount: (count: string) => `${count} خزمەتگوزاری هەڵبژێردراوە`,
    paginationRange: (from: string, to: string, total: string) =>
      `ڕیزی ${from}–${to} لە ${total}`,
    collectionCount: (count: string) => `${count} کۆکراوە`,
    fileCount: (count: string) => `${count} فایل`,
  },
  lang: {
    ckb: "سۆرانی",
    kmr: "کورمانجی",
    ckbShort: "CKB",
    kmrShort: "KMR",
  },
  empty: {
    no_services: {
      title: "هیچ خزمەتگوزارییەک نییە",
      subtitle: "یەکەم خزمەتگوزاریت دروست بکە بۆ دەستپێکردن",
    },
    no_collections: {
      title: "هیچ کۆکراوەیەک نییە",
      subtitle:
        "کۆکراوەی نوێ دروست بکە بۆ ڕێکخستنی وێنە، ڤیدیۆ یان دەنگەکانت.",
    },
    no_results: {
      title: "هیچ ئەنجامێک نەدۆزرایەوە",
      subtitle: "هەوڵبدە کلیلەوشە یان فلتەرەکانت بگۆڕیت",
      cta: "پاککردنەوەی فلتەرەکان",
    },
    no_cover: "بێ وێنەی ڕووکار",
    no_body: "وەسف بۆ ئەم زمانە بەردەست نییە.",
  },
  not_found: {
    title: "خزمەتگوزاری نەدۆزرایەوە",
    cta: "گەڕانەوە بۆ لیست",
  },
  toast: {
    created: "خزمەتگوزاری بەسەرکەوتوویی دروستکرا",
    updated: "خزمەتگوزاری بەسەرکەوتوویی نوێکرایەوە",
    saved: "خزمەتگوزاری بەسەرکەوتوویی پاشەکەوتکرا",
    deleted: "خزمەتگوزاری سڕایەوە",
    bulkDeleted: (count: string) => `${count} خزمەتگوزاری سڕایەوە`,
    copied: "لەبەرگیرایەوە",
    viewAction: "بینین",
  },
  dialog: {
    deleteTitle: "سڕینەوەی ئەم خزمەتگوزارییە؟",
    deleteBody:
      "ئەم کردارە ناتوانرێت بگەڕێندرێتەوە. خزمەتگوزارییەکە بەو هەموو کۆکراوە و فایلەکانییەوە لە S3 بۆ هەمیشە دەسڕێتەوە.",
    bulkDeleteBody: (count: string) =>
      `${count} خزمەتگوزاری بۆ هەمیشە دەسڕێتەوە بەو هەموو فایلەکانییەوە.`,
  },
  unsaved: {
    indicator: "گۆڕانکارییە پاشەکەوتنەکراوەکان",
  },
  help: {
    saveRequirements: "بۆ پاشەکەوتکردن: جۆر، لانیکەم زمانێک و ناونیشان پێویستن.",
    langStatusCkb: "سۆرانی — ناونیشان پێویستە",
    langStatusKmr: "کورمانجی",
  },
  summary: {
    type: "جۆر",
    collections: "کۆکراوەکان",
    files: "فایلەکان",
    cover: "کافەر",
    coverSet: "هەڵبژێردراوە",
    none: "نییە",
  },
  system: {
    id: "ناسنامە",
    createdAt: "دروستکراوە",
    updatedAt: "نوێکراوەتەوە",
    publishDate: "بەرواری بڵاوکردنەوە",
  },
  upload: {
    pending: "بارکراوە…",
    failed: "بارکردن سەرکەوتوو نەبوو",
    retry: "دووبارە هەوڵبدەرەوە",
    tooLarge: "قەبارەی فایلەکە زۆرە",
  },
  validation: {
    languageRequired: "زمانێک پێویستە",
    titleRequired: "ناونیشان پێویستە",
    collectionNameRequired: "ناوی کۆکراوە پێویستە",
    mediaTypeRequired: "جۆری میدیا هەڵبژێرە",
  },
} as const

export function truncateTitle(text: string, max = 40): string {
  const t = text.trim()
  if (t.length <= max) return t
  return `${t.slice(0, max)}…`
}
