/** Central CKB copy for the services module (verbatim from spec §11). */

export const NS = {
  dash: "—",
  error: {
    generic: "هەڵەیەک ڕوویدا. دووبارە هەوڵبدەرەوە.",
    validation: "تکایە بەشە پڕنەکراوەکان پڕ بکەرەوە.",
    heroSave: "پاشەکەوتکردنی هێرۆ سەرکەوتوو نەبوو.",
    retry: "دووبارە هەوڵبدەرەوە",
  },
  page: {
    title: "پەڕەی خزمەتگوزاری",
    subtitle:
      "هەر بەشێک = یەک scroll section لە /services لە سایتدا. زیاد بکە، دواتر زانیارییەکەی پڕ بکەرەوە.",
    subtitleSimple:
      "سەرەوە هێرۆی پەڕەکە — خوارەوە بەشەکان یەک بە یەک (ناونیشان، دەق، گالەری).",
    heroTitle: "هێرۆی پەڕە",
    heroHint: "وێنە، دەقی سەر ناونیشان، ناونیشان، وەسفی کورت.",
    heroImage: "وێنەی هێرۆ",
    heroOvertitle: "دەقی سەر ناونیشان (overtitle)",
    heroOvertitlePlaceholder: "خزمەتگوزارییەکانمان…",
    heroSubtitle: "وەسفی کورت (subtitle)",
    sectionsTitle: "بەشەکان",
    sectionLabel: (n: string) => `بەش ${n}`,
    siteNavHint:
      "ئەم لیستە وەک ناوبری چەپ لە سایت دەردەکەوێت — ڕیز و ناونیشان لەوێ دەردەکەوێت.",
    panelTitleNew: "بەشی نوێ",
    panelTitleEdit: "دەستکاری بەش",
    fieldTitle: "ناونیشان",
    fieldBody: "ناوەڕۆک",
    panelPlaceholder:
      "«زیادکردنی بەش» کلیک بکە، یان بەشێک لە لیست هەڵبژێرە بۆ دەستکاری زانیاری.",
    previewMode: "پیشاندانی پەڕە",
    previewHint: "ئەمە وەک پەڕەی /services لە سایت دەردەکەوێت.",
    previewHeroEmpty: "هێرۆی پەڕە هێشتا دانەنراوە.",
  },
  breadcrumb: {
    dashboard: "داشبۆرد",
    services: "خزمەتگوزارییەکان",
    new: "خزمەتگوزاری نوێ",
    edit: "دەستکاری خزمەتگوزاری",
  },
  action: {
    new: "خزمەتگوزاری نوێ",
    addSection: "زیادکردنی بەش",
    editSectionData: "دەستکاری زانیاری بەش",
    backToSections: "گەڕانەوە بۆ لیستی بەشەکان",
    view: "بینین",
    edit: "دەستکاری",
    delete: "سڕینەوە",
    back: "گەڕانەوە",
    save: "پاشەکەوتکردن",
    saveHero: "پاشەکەوتکردنی هێرۆ",
    editPage: "دەستکاری پەڕە",
    backToPreview: "گەڕانەوە بۆ پیشاندان",
    saving: "پاشەکەوتکردن…",
    cancel: "هەڵوەشاندنەوە",
    change: "گۆڕین",
    reset_filters: "پاککردنەوەی فلتەرەکان",
    add_collection: "کۆکراوەی نوێ",
    add_first_collection: "یەکەم کۆکراوە",
    add_file: "زیادکردنی فایل",
    copy_url: "لەبەرگرتنەوەی ناونیشانی URL",
    share: "هاوبەشکردن",
    view_on_site: "بینین لە سایت",
    publish_now: "ئێستا بڵاوبکەوە",
    clear_publish: "پاککردنەوە",
    bulk_delete: "سڕینەوەی هەڵبژێردراوەکان",
    bulk_cancel: "هەڵوەشاندنەوەی هەڵبژاردن",
    remove_cover: "سڕینەوە",
    use_url_instead: "یان لینکی URL بەکاربهێنە",
    upload: "بارکردن",
    upload_files: "بارکردنی فایلەکان",
    add_file_by_url: "زیادکردنی فایل بە URL",
    create: "دروستکردن",
  },
  filter: {
    search_placeholder: "گەڕان لە ناونیشان، ئەنکەر، شوێن، یان جۆر",
    all_statuses: "هەموو دۆخەکان",
    published: "بڵاوکراوە",
    draft: "ڕەشنووس",
    all_types: "هەموو جۆرەکان",
    all_active: "هەردووکیان",
    only_active: "تەنیا چالاک",
    only_inactive: "تەنیا ناچالاک",
    lang_ckb_only: "تەنیا سۆرانی",
    lang_kmr_only: "تەنیا کورمانجی",
    lang_both: "هەردووکیان",
  },
  status: {
    published: "بڵاوکراوە",
    scheduled: "کاتبۆداندراو",
    draft: "ڕەشنووس",
    inactive: "ناچالاک",
    contextPublished: (date: string) => `بڵاوکراوەتەوە لە ${date}`,
    contextScheduled: (date: string) => `کاتبۆداندراوە بۆ ${date}`,
    contextDraft: "ڕەشنووس — لە چاوەڕێی بڵاوکردنەوەدا",
    contextInactive: "ناچالاککراوە",
  },
  active: {
    label: "چالاک",
    on: "چالاکە",
    off: "ناچالاکە",
    helper: "ناچالاککردن خزمەتگوزارییەکە لە سایتدا نادیار دەکات بەبێ ئەوەی بسڕدرێتەوە.",
    formHelper: "خزمەتگوزاری ناچالاک لە سایتدا دەرناکەوێت",
    toggleOn: "چالاک کرا",
    toggleOff: "ناچالاک کرا",
  },
  col: {
    cover: "ڕووکار",
    title: "ناونیشان",
    type: "جۆر",
    anchor: "ئەنکەر",
    layout: "شێوازی نیشاندان",
    sortOrder: "ڕیز",
    status: "دۆخ",
    location: "شوێن",
    published: "بەرواری بڵاوکردنەوە",
    updated: "نوێکراوەتەوە",
    media: "میدیا",
    actions: "کردارەکان",
  },
  section: {
    visibility: "چالاکی",
    publish: "بەرواری بڵاوکردنەوە",
    type: "جۆری خزمەتگوزاری",
    location: "شوێن",
    languages: "زمانەکان",
    dates: "بەروارەکان",
    system: "زانیاری سیستەم",
    actions: "کردارەکان",
    collections: "کۆکراوەکانی میدیا",
    collectionsDetail: "کۆکراوەکان",
    general: "ڕێکخستنی بەش",
    languageContent: "ناونیشان و ناوەڕۆک",
    optionalSettings: "ڕێکخستنی ئارەزوومەندانە",
    unnamed: "بەشی بێ ناونیشان",
    coverHero: "کافەر / هێرۆ",
    media: "میدیا",
    mediaCollections: "کۆمەڵە میدیاکان",
    partners: "هاوبەشەکان",
    layout: "شێوازی نیشاندان",
    publishing: "بڵاوکردنەوە",
  },
  layout: {
    MEDIA_HERO: "هێرۆی میدیا",
    FEATURE_GRID: "تۆڕی گالەری",
    DEFAULT: "سەرنووسەری",
    hintMediaHero:
      "گالەری بە ڕیز — دەتوانیت ڤیدیۆ لە هەر شوێنێکی لیستدا بخەیت.",
    hintFeatureGrid:
      "گالەری وێنە بە ڕیز — بۆ بەشەکانی وێنە-قورس.",
    hintDefault: "شێوازی سادە — ناوەڕۆک + گالەری بە ڕیز.",
  },
  field: {
    titleCkb: "ناونیشانی خزمەتگوزاری بە سۆرانی…",
    titleKmr: "Sernavê xizmetê bi Kurmancî…",
    bodyCkb: "وەسفی خزمەتگوزارییەکەت لێرە بنووسە…",
    bodyKmr: "Vekolîna xizmeta xwe li vir binivîse…",
    bodyHelper:
      "بە Markdown بنووسە. لە پەڕەی خزمەتگوزارییەکان وەک نووسینی دەوڵەمەند پیشان دەدرێت.",
    location: "شوێن یان ئامادەبوون لە ئەنڵاین…",
    locationHelper: "(تەنیا یەک شوێن بۆ هەردوو زمان)",
    typeHelper: "ئارەزوومەندانە — ناونیشانی کورت یان پۆلی بەش.",
    typeRequired: "جۆری خزمەتگوزاری پێویستە",
    navAnchor: "لینکی قووڵ (#anchor)",
    navAnchorHelper:
      "slug بۆ لینکی ناوبری، وەک recording-studio. ئەگەر بەتاڵ بێت سایت ID بەکاردەهێنێت.",
    navAnchorPlaceholder: "recording-studio",
    featureDescriptionCkb: "کورتەیەکی سادە بۆ سلایدی سەرەکی…",
    featureDescriptionKmr: "Kurteyeke sade ji bo slaytê…",
    featureDescriptionLabel: "دەقی سلایدی سەرەکی",
    featureDescriptionHelper:
      "لە کاروسێلی پەڕەی سەرەکی بەکاردێت. دەقی سادە — ئەگەر بەتاڵ بێت کورتەیەک لە وەسفەکە دەبڕدرێت.",
    heroVideo: "ڤیدیۆی هێرۆ",
    heroPoster: "پۆستەری ڤیدیۆ",
    featureImages: "وێنەکانی تایبەتمەندی",
    featureImagesHelper: "یەکەم وێنە وەک وێنەی سەرەکی بەکاردێت.",
    thumbnails: "وێنەکانی گالەری (thumbnail)",
    thumbnailsHelper: "سایت تا ٤ وێنە چاوەڕوان دەکات.",
    thumbnailsWarn: "زیاتر لە ٤ وێنە — سایت تەنیا چواری یەکەم بەکاردەهێنێت.",
    partnersHelper: "هاوبەشەکانی خوارەوەی پەڕەی خزمەتگوزارییەکان.",
    partnersEmpty: "هیچ هاوبەشێک لە بەشی Aboutدا نییە.",
    addImage: "زیادکردنی وێنە",
    publishHelper:
      "بەرواری داهاتوو واتە کاتبۆداندراو، بەرواری ڕابردوو واتە بڵاوکراوە.",
    coverDrop: "وێنە و فایلەکانت دابنێ یان کلیک بکە بۆ هەڵبژاردن",
    coverHelper: "PNG، JPEG، WEBP یان MP4 · زۆرترین قەبارە ٢٠ MB",
    coverNotSelected: "کافەر هەڵنەبژێردراوە",
    coverMediaUrl: "coverMediaUrl",
    sortOrder: "sortOrder",
    sortOrderLabel: "ڕیز لە ناوبری سایت",
    sortOrderHelper:
      "ژمارەی کەمتر = لە پێشەوە لە ناوبری پەڕەی /services. بەتاڵ = لە کۆتایی.",
    thumbnailUrl: "thumbnailUrl",
    fileUrl: "fileUrl",
  },
  gallery: {
    section: "گالەری میدیا",
    sectionHelper:
      "ڕیزبەندی ئەم لیستە = filmstrip لە سایتدا. یەکەم ئایتەم گەورەتر دەردەکەوێت.",
    empty: "هیچ فایلێک زیاد نەکراوە — فایل بار بکە یان بە URL زیاد بکە.",
    addImage: "زیادکردنی وێنە",
    addVideo: "زیادکردنی ڤیدیۆ",
    editSlot: (index: string) => `فایل ${index}`,
    pickOrUpload: "فایلێک هەڵبژێرە یان بار بکە",
    addSlot: "زیادکردن",
    sheetTitle: (index: string) => `دەستکاری فایل #${index}`,
    typeImage: "وێنە",
    typeVideo: "ڤیدیۆ",
    url: "ناونیشانی URL",
    posterUrl: "پۆستەری ڤیدیۆ",
    alt: "دەقی جێگرەوە (alt)",
    altPlaceholder: "وەسفی کورت بۆ دەستپێگەیشتن…",
    bulkDrop: "وێنە یان ڤیدیۆ بکێشە ئێرە — یان کلیک بکە بۆ هەڵبژاردنی چەند فایل",
    bulkHelper: "دەتوانیت چەند فایلێک یەکجار بار بکەیت",
    bulkProcessing: (count: string) => `بارکردنی ${count} فایل…`,
    bulkMax: (max: string) => `زۆرترین ${max} فایل`,
    noUrl: "بێ URL",
  },
  collection: {
    namePlaceholder: "ناوی کۆکراوە…",
    mediaTypeImage: "وێنە",
    mediaTypeVideo: "ڤیدیۆ",
    mediaTypeAudio: "دەنگ",
    mediaTypeLabel: "جۆری میدیا",
    addButton: "زیادکردن",
    fileCount: (count: string) => `${count} فایل`,
    emptyFiles: "هیچ فایلێک لەم کۆکراوەیەدا نییە",
    deleteTitle: "سڕینەوەی ئەم کۆکراوەیە؟",
    deleteBody: (count: string) => `${count} فایلیش لەگەڵیدا دەسڕێتەوە.`,
    newSection: "کۆکراوەکانی میدیا",
    sortOrderLabel: "ڕیزکردن",
  },
  file: {
    sheetTitle: "دەستکاری فایل",
    caption: "نووسە",
    title: "ناونیشان",
    description: "وەسف",
    captionPlaceholder: "نووسەی کورت لەژێر وێنەدا…",
    titlePlaceholder: "ناونیشانی فۆڕماڵ…",
    metadataTitle: "زانیاری تەکنیکی",
    metadataFormat: "فۆڕمات",
    metadataResolution: "پاژەکی",
    metadataDuration: "ماوە",
    metadataCodec: "کۆدیک",
    metadataBitrate: "بایترەیت",
    metadataSize: "قەبارە",
    metadataAutoTooltip: "زانیاری بە شێوەی خۆکار دۆزراوەتەوە",
    delete: "سڕینەوەی فایل",
    captionCkb: "نووسە CKB",
    titleCkb: "ناونیشان CKB",
    descriptionCkb: "وەسف CKB",
    captionKmr: "نووسە KMR",
    titleKmr: "ناونیشان KMR",
    descriptionKmr: "وەسف KMR",
    editInline: "دەستکاری لە فۆڕم",
    openSheet: "کردنەوەی پانێڵی تەواو",
  },
  list: {
    sectionsHeading: "بەشەکان",
    totalCount: (count: string) => `کۆی ${count} بەش`,
    selectedCount: (count: string) => `${count} بەش هەڵبژێردراوە`,
    paginationRange: (from: string, to: string, total: string) =>
      `ڕیزی ${from}–${to} لە ${total}`,
    collectionCount: (count: string) => `${count} کۆکراوە`,
    fileCount: (count: string) => `${count} فایل`,
  },
  lang: {
    ckb: "سۆرانی",
    kmr: "کورمانجی",
    ckbShort: "CKB",
    kmrShort: "KMR",
  },
  empty: {
    no_services: {
      title: "هیچ بەشێک نییە",
      subtitle: "یەکەم بەش زیاد بکە، دواتر ناونیشان و ناوەڕۆکی پڕ بکەرەوە",
    },
    no_collections: {
      title: "هیچ کۆکراوەیەک نییە",
      subtitle:
        "کۆکراوەی نوێ دروست بکە بۆ ڕێکخستنی وێنە، ڤیدیۆ یان دەنگەکانت.",
    },
    no_results: {
      title: "هیچ ئەنجامێک نەدۆزرایەوە",
      subtitle: "هەوڵبدە کلیلەوشە یان فلتەرەکانت بگۆڕیت",
      cta: "پاککردنەوەی فلتەرەکان",
    },
    no_cover: "بێ وێنەی ڕووکار",
    no_body: "وەسف بۆ ئەم زمانە بەردەست نییە.",
  },
  not_found: {
    title: "خزمەتگوزاری نەدۆزرایەوە",
    cta: "گەڕانەوە بۆ لیست",
  },
  toast: {
    created: "خزمەتگوزاری بەسەرکەوتوویی دروستکرا",
    updated: "خزمەتگوزاری بەسەرکەوتوویی نوێکرایەوە",
    saved: "خزمەتگوزاری بەسەرکەوتوویی پاشەکەوتکرا",
    heroSaved: "هێرۆی پەڕە پاشەکەوتکرا",
    deleted: "خزمەتگوزاری سڕایەوە",
    bulkDeleted: (count: string) => `${count} خزمەتگوزاری سڕایەوە`,
    copied: "لەبەرگیرایەوە",
    viewAction: "بینین",
  },
  dialog: {
    deleteTitle: "سڕینەوەی ئەم خزمەتگوزارییە؟",
    deleteBody:
      "ئەم کردارە ناتوانرێت بگەڕێندرێتەوە. خزمەتگوزارییەکە بەو هەموو کۆکراوە و فایلەکانییەوە لە S3 بۆ هەمیشە دەسڕێتەوە.",
    bulkDeleteBody: (count: string) =>
      `${count} خزمەتگوزاری بۆ هەمیشە دەسڕێتەوە بەو هەموو فایلەکانییەوە.`,
  },
  unsaved: {
    indicator: "گۆڕانکارییە پاشەکەوتنەکراوەکان",
  },
  help: {
    formIntro:
      "هەر خزمەتگوزارییەک = یەک بەش لە پەڕەی /ckb/services یان /ku/services. ناونیشان و دەق لە contents[] دەچێتە سایت. بەبێ ناونیشان بۆ زمانەکە، بەشەکە لەو زمانە نیشان نادرێت.",
    saveRequirements:
      "بۆ پاشەکەوتکردن: لانیکەم ناونیشانێک بۆ یەکێک لە زمانە هەڵبژێردراوەکان پێویستە.",
    langStatusCkb: "سۆرانی — ناونیشان پێویستە",
    langStatusKmr: "کورمانجی — ناونیشان پێویستە",
  },
  summary: {
    type: "جۆر",
    anchor: "ئەنکەر",
    layout: "شێواز",
    sortOrder: "ڕیز",
    collections: "کۆکراوەکان",
    files: "فایلەکان",
    cover: "کافەر",
    coverSet: "هەڵبژێردراوە",
    none: "نییە",
  },
  system: {
    id: "ناسنامە",
    createdAt: "دروستکراوە",
    updatedAt: "نوێکراوەتەوە",
    publishDate: "بەرواری بڵاوکردنەوە",
  },
  upload: {
    pending: "بارکراوە…",
    failed: "بارکردن سەرکەوتوو نەبوو",
    retry: "دووبارە هەوڵبدەرەوە",
    tooLarge: "قەبارەی فایلەکە زۆرە",
  },
  validation: {
    languageRequired: "زمانێک پێویستە",
    titleRequired: "ناونیشان پێویستە",
    collectionNameRequired: "ناوی کۆکراوە پێویستە",
    mediaTypeRequired: "جۆری میدیا هەڵبژێرە",
    navAnchorInvalid:
      "ئەنکەر دەبێت بە شێوازی slug بێت (a-z، ٠–٩، و -)، وەک institute-hall",
    urlInvalid: "ناونیشانی URL نادروستە",
    thumbnailsMax: "زۆرترین ٤ وێنەی thumbnail پێشنیارکراوە",
  },
} as const

export function truncateTitle(text: string, max = 40): string {
  const t = text.trim()
  if (t.length <= max) return t
  return `${t.slice(0, max)}…`
}
