export const NS = {
  title: "دەربارەکان",
  subtitle: "بینین، گەڕان و بەڕێوەبردنی هەموو پەرەکانی دەربارە",
  count: (n: string) => `کۆی ${n} دەربارە`,
  new: "دەربارەی نوێ",
  search_placeholder: "گەڕان لە ناونیشان، ژێرناونیشان، یان سلەگ…",
  filter: {
    status_all: "هەموو دۆخەکان",
    lang_all: "هەموو زمانەکان",
    reset: "پاککردنەوە",
  },
  status: {
    draft: "ڕەشنووس",
    active: "چالاک",
    archived: "ئەرشیفکراو",
    draft_helper: "پەرەکە لەسەر ماڵپەڕ دەردەکەوێت تەنها کاتێک چالاک بێت.",
    active_helper: "پەرەکە لەسەر ماڵپەڕ بەردەستە.",
    archived_helper: "پەرەکە لە لیستی گشتی شارداوەتەوە.",
  },
  lang: {
    ckb: "سۆرانی",
    kmr: "کورمانجی",
  },
  table: {
    hero: "",
    id: "#",
    slugs: "سلەگەکان",
    title: "ناونیشان",
    blocks: "بلۆک",
    language: "زمان",
    status: "دۆخ",
    date: "بەروار",
    actions: "",
  },
  slug: {
    missing: "سلەگ نییە",
    copy_title: "کلیک بکە بۆ لەبەرگرتنەوەی ناونیشانی URL",
  },
  pagination: {
    range: (from: string, to: string, total: string) =>
      `ڕیزی ${from}–${to} لە ${total}`,
  },
  action: {
    view: "بینین",
    edit: "دەستکاری",
    delete: "سڕینەوە",
    back: "گەڕانەوە",
    view_site: "بینین لە سایت",
    save: "پاشەکەوتکردن",
    saving: "پاشەکەوتکردن…",
    cancel: "هەڵوەشاندنەوە",
    copy_url: "لەبەرگرتنەوەی ناونیشانی URL",
    copy_page: "کۆپی کردنی پەرە",
    archive: "ئەرشیفکردن",
  },
  breadcrumb: {
    dashboard: "داشبۆرد",
    about: "دەربارەکان",
    new: "دەربارەی نوێ",
    edit: "دەستکاری",
  },
  detail: {
    no_hero: "بێ وێنەی هیرۆ",
    blocks: "بلۆکەکان",
    block_count: (n: string) => `${n} بلۆک`,
    seo: "وەسفی میتا (SEO)",
  },
  sidebar: {
    page_status: "دۆخی پەرە",
    slugs: "سلەگەکان",
    seo: "زانیاری SEO",
    seo_title: "ناونیشان",
    seo_desc: "وەسف",
    blocks: "بلۆکەکان",
    total: "کۆ",
    actions: "کردارەکان",
    completion: "تەواوبوون",
    completion_hint:
      "تەواو: ناونیشان، ژێرناونیشان، وەسفی SEO، لانیکەم یەک بلۆک",
    languages: "زمانەکان",
    system: "زانیاری سیستەم",
    id: "ناسنامە",
    created: "دروستکراوە",
    updated: "نوێکراوەتەوە",
  },
  form: {
    hero: "وێنەی هیرۆ",
    hero_shared: "— هاوبەش بۆ هەر دوو زمان",
    hero_hint:
      "وێنەی بانەر — پێشنیار:",
    hero_empty: "وێنەی هیرۆ هەڵنەبژێردراوە",
    hero_drop: "وێنە دابنێ یان کلیک بکە بۆ هەڵبژاردن",
    hero_size: "پێشنیاری پێوانە: 1600 × 600px",
    hero_change: "گۆڕین",
    hero_remove: "سڕینەوە",
    url_fallback: "یان لینکی URL بەکاربهێنە",
    url_load: "بارکردن",
    slugs: "سلەگەکان",
    slug_ckb: "سلەگی سۆرانی",
    slug_kmr: "سلەگی کورمانجی",
    slug_ckb_hint: "ناسەری URL — کاراکتەری ASCII یان کوردی",
    slug_kmr_hint: "ئەگەر بۆشێت، سلەگی سۆرانی بەکاردێت",
    slug_required: "پێویستە",
    slug_optional: "ئیختیاری",
    title: "ناونیشان",
    subtitle: "ژێرناونیشان",
    seo: "وەسفی میتا (SEO)",
    seo_preview: "پێشبینین لە گووگل:",
    seo_fallback: "وەسفی پەرە لێرە دەردەکەوێت…",
    blocks: "بلۆکەکانی پەرە",
    blocks_empty_title: "پەرەکەت بە یەکەم بلۆک دەستپێبکە",
    blocks_empty_desc:
      "هەر بلۆکێک پارچەیەکی ناوەرۆکە — نووسە، وێنە، ڤیدیۆ، گالەری، وتە، یان ئامار",
    add_block: "بلۆکی نوێ زیاد بکە:",
    dirty: "گۆڕانکارییە پاشەکەوتنەکراوەکان",
    clean: "هیچ گۆڕانکارییەک نییە",
  },
  block: {
    text: "دەق",
    image: "وێنە",
    video: "ڤیدیۆ",
    audio: "دەنگ",
    gallery: "گالەری",
    quote: "وتە",
    stat: "ئامار",
  },
  validation: {
    languageRequired: "لانیکەم یەک زمان هەڵبژێرە",
    slugCkbRequired: "سلەگی سۆرانی پێویستە",
    titleCkbRequired: "ناونیشانی سۆرانی پێویستە",
    titleKmrRequired: "ناونیشانی کورمانجی پێویستە",
    blocksRequired: "لانیکەم یەک بلۆک پێویستە",
  },
  toast: {
    saved: "پاشەکەوت کرا",
    copied: "لینک لەبەرگرتەوە",
    deleted: "سڕایەوە",
    view_action: "بینین",
  },
  error: {
    validation: "تکایە هەڵەکان چاک بکە",
    load: "بارکردن سەرکەوتوو نەبوو",
    retry: "دووبارە هەوڵبدەرەوە",
  },
  not_found: {
    title: "پەرەکە نەدۆزرایەوە",
    cta: "گەڕانەوە بۆ لیست",
  },
  delete: {
    title: "سڕینەوەی پەرەی دەربارە",
    description: (name: string) =>
      `دڵنیایت لە سڕینەوەی «${name}»؟ ئەم کردارە ناگەڕێتەوە.`,
    confirm: "دڵنیام",
    cancel: "هەڵوەشاندنەوە",
  },
} as const

export function truncateTitle(s: string, max = 48) {
  const t = s.trim()
  if (t.length <= max) return t
  return `${t.slice(0, max)}…`
}
